### ISSUE TITLE
Создание страницы с информациях о врачах

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-frontend#10]
Необходимо показать всю доступную на данный момент информацию о врачах, остальное заменить текстом как на картинке
![Screenshot_263](https://user-images.githubusercontent.com/1532675/139325317-449ddef5-263c-4758-abd7-2466eb3a105f.png)

**Comment by CocoaHoto** [comment]
![Screenshot_427](https://user-images.githubusercontent.com/56096644/143890243-1e1a6130-5745-4b06-b0ca-b89fbabd3f19.png)
Информация о врачах была показана
