### ISSUE TITLE
Вход пользователя

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-frontend#11]
Необходимо отправить данные для входа (логин и пароль) отправить на проверку в backend, затем получить ответ, в случае если пароль неверный, должен появится текст неверный пароль.
![Screenshot_266](https://user-images.githubusercontent.com/1532675/139325669-a0a1d3b5-5b71-470f-903b-1aa3033239af.png)

**Comment by CocoaHoto** [comment]
Для заполнения необходимо ввести логин и пароль. Далее отправляется запрос на backend. При положительном ответе от backend пользователь входить в систему, а при неправильной авторизации выходит соответствующее уведомление. 
![Screenshot_483](https://user-images.githubusercontent.com/56096644/145096254-7600774b-3ff5-49a9-b473-d730080e9069.png)
![Screenshot_484](https://user-images.githubusercontent.com/56096644/145096264-d915d786-c1c4-4847-b956-243ccc9ce923.png)
 Вывод в консоли об ошибке при авторизации:

![Screenshot_485](https://user-images.githubusercontent.com/56096644/145096360-0a0b3ae9-63e6-436d-9bdf-17f75c1cce44.png)

**Comment by reshat** [comment]
![Screenshot_495](https://user-images.githubusercontent.com/1532675/146162174-377758a6-1b8e-4371-a251-37217221750a.png)
При неправильном вводе пароля.
При правильном вводе логина и пароля окно закрывается, авторизация работает
