### ISSUE TITLE
Fix CORS policies

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-frontend#13]
![Screenshot_270](https://user-images.githubusercontent.com/1532675/139592341-1f2de41d-30c7-4c9e-8179-dfdac8e23d02.png)
Нужно сделать так, чтобы приложение работало на любом устройстве, для этого нужно настроить CORS

**Comment by CocoaHoto** [comment]
CORS должен принимать header из backend. Необходимо исправить его со стороны backend
![Screenshot_312](https://user-images.githubusercontent.com/56096644/140967960-82796151-be0e-41c2-a841-ce4c1a7d0fbe.png)
.
