### ISSUE TITLE
Создание меню

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-frontend#2]
Необходимо сделать меню, содержащее три пункта, как на рисунке, по каждому из которых можно переходить.
![Screenshot_60](https://user-images.githubusercontent.com/1532675/134807329-7428441a-965f-4d84-a9f9-263e9fd00522.png)

**Comment by CocoaHoto** [comment]
Было добавлено меню.
Была добавлена возможность переходить по пунктам меню

**Comment by CocoaHoto** [comment]
![Screenshot_287](https://user-images.githubusercontent.com/56096644/140571810-d51f167a-5a20-429f-9033-5e06adf97690.png)
![Screenshot_288](https://user-images.githubusercontent.com/56096644/140571820-d9cb3011-0fbc-4aec-8780-e08f564703ab.png)
![Screenshot_289](https://user-images.githubusercontent.com/56096644/140571833-c0243d32-c9aa-46cb-b206-a868176ee3be.png)

**Comment by reshat** [comment]
Неплохо бы еще добавлять что нужно установить для запуска
npm install --save vue-router
npm install ant-design-vue или какой?

**Comment by CocoaHoto** [comment]
Да, необходимо добавить vue router: npm add router
А еще добавить ant design:   npm install ant-design-vue --save
npm i --save ant-design-vue@next

**Comment by reshat** [comment]
Еще нужно установить 
npm i vue-router@nex
![Screenshot_282](https://user-images.githubusercontent.com/1532675/140603197-d1b7467e-4f82-487c-bd0d-9c4fc28ace07.png)
![Screenshot_281](https://user-images.githubusercontent.com/1532675/140603200-4dbdf5a3-d8fa-4c90-9735-c367ae582460.png)
t
