### ISSUE TITLE
Заполнение пункта меню Общая информация

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-frontend#3]
Необходимо получить данные из backend, и по ним заполнить пункт меню

**Comment by CocoaHoto** [comment]
![Screenshot_331](https://user-images.githubusercontent.com/56096644/141497795-11360e20-6797-445e-8760-8702ffeffe0e.png)
Данные из backend получаются на frontend и заполняется пункт меню.

**Comment by reshat** [comment]
![Screenshot_349](https://user-images.githubusercontent.com/1532675/142378468-d7ec8799-2798-4f4f-8bfe-bf2c4eb05a8e.png)
Информация действительно заполняется
