### ISSUE TITLE
Изменение общего вида приложения

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-frontend#7]
![Screenshot_262](https://user-images.githubusercontent.com/1532675/139324780-1e5f1ad0-1977-4ccb-8a85-448b3b3ee8f6.png)
Нужно сделать так, как на скриншоте, картинки предоставлены снизу
![Screenshot_261](https://user-images.githubusercontent.com/1532675/139324825-8b20b805-b192-429c-8d07-9bc060829957.png)
![Screenshot_260](https://user-images.githubusercontent.com/1532675/139324842-f61bfbb7-c641-465b-aacc-1ac5734852f0.png)

**Comment by CocoaHoto** [comment]
![Screenshot_338](https://user-images.githubusercontent.com/56096644/142015092-0d4b7461-48e4-4a2a-ab3e-842241ecd1da.png)
Изменен общий вид приложения

**Comment by reshat** [comment]
Цвет текста слева сделай черным

**Comment by CocoaHoto** [comment]
![Screenshot_338](https://user-images.githubusercontent.com/56096644/142016834-30db52cb-ef72-448d-b829-3351b31fe6f8.png)
Сделано

**Comment by reshat** [comment]
![Screenshot_349](https://user-images.githubusercontent.com/1532675/142378675-3eebbcff-64c9-4535-afde-d2cd3a41ff29.png)
Появились на проде
