### ISSUE TITLE
Добавление окна

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-frontend#8]
При наведении мышки на окно пользователя(кружок в правом верхнем углу приложения), должно появиться следующее меню
![Screenshot_264](https://user-images.githubusercontent.com/1532675/139325062-792ad06c-a20c-4450-bc3e-9c3c2446f79a.png)

**Comment by CocoaHoto** [comment]
На скриншоте ниже реализовано окно для входа в систему. При нажатии на кнопку "Войти" открывается окно авторизации.
![Screenshot_482](https://user-images.githubusercontent.com/56096644/145095597-e49be0bc-b846-4022-a640-d3e24269278a.png)

**Comment by reshat** [comment]
![Screenshot_493](https://user-images.githubusercontent.com/1532675/146161850-36389348-a186-435e-8fba-f11b2e1a9b38.png)
Окно отображается при наведении на кнопку
